import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — MusicDNA" },
      {
        name: "description",
        content: "The rules and agreements for using MusicDNA.",
      },
      { property: "og:title", content: "Terms of Service — MusicDNA" },
      {
        property: "og:description",
        content: "The rules and agreements for using MusicDNA.",
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="border-b hairline">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
          <Link to="/" className="flex items-center gap-3">
            <Mark />
            <span className="sr-only">MusicDNA</span>
          </Link>
          <Link
            to="/"
            className="font-mono text-[11px] uppercase tracking-[0.18em] text-muted-foreground transition-colors hover:text-foreground"
          >
            ← Back
          </Link>
        </div>
      </header>

      <article className="mx-auto max-w-3xl px-6 py-16">
        <p className="eyebrow mb-4">App-maintained agreement</p>
        <h1 className="display text-4xl md:text-5xl mb-8">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-12">
          Last updated: July 1, 2026. By using MusicDNA, you agree to these terms. If you don't agree, don't use the service.
        </p>

        <div className="space-y-12">
          <section>
            <h2 className="display text-2xl mb-3">The service</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              MusicDNA is a self-discovery platform that uses your music choices to generate personal insights, interpretations, and reads. We are not a recommendation engine, a streaming service, or a licensed music provider. We do not play or distribute songs.
            </p>
          </section>

          <section>
            <h2 className="display text-2xl mb-3">Accounts</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              You can use MusicDNA anonymously or create an account. You are responsible for keeping your login credentials secure. We are not liable for unauthorized access to your account caused by credential sharing or weak passwords.
            </p>
          </section>

          <section>
            <h2 className="display text-2xl mb-3">Acceptable use</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Do not use MusicDNA to harass, abuse, or target others. Do not attempt to reverse-engineer the system, scrape data, or interfere with the service's operation. Do not submit content that infringes on intellectual property or violates applicable law.
            </p>
          </section>

          <section>
            <h2 className="display text-2xl mb-3">Content and ownership</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              You retain ownership of the content you submit (song names, messages, etc.). By submitting it, you grant us a limited license to process it for the purpose of generating your read and improving the service. The reads, interpretations, and generated text we produce are our original creative output, made available to you for personal, non-commercial use.
            </p>
          </section>

          <section>
            <h2 className="display text-2xl mb-3">Sharing</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Share links are public by design. Anyone with the link can view the anonymized read. You are responsible for who you share it with. You can delete a share link at any time.
            </p>
          </section>

          <section>
            <h2 className="display text-2xl mb-3">Disclaimers</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              MusicDNA's reads are generated by AI and are meant for entertainment and reflection, not as professional advice, diagnosis, or fact. We do not guarantee accuracy, completeness, or that any read will resonate with you. The service is provided "as is" without warranties of any kind.
            </p>
          </section>

          <section>
            <h2 className="display text-2xl mb-3">Limitation of liability</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              To the fullest extent permitted by law, MusicDNA and its operators are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability is limited to the amount you paid us in the twelve months preceding the claim — or zero, if you used the service for free.
            </p>
          </section>

          <section>
            <h2 className="display text-2xl mb-3">Termination</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              We may suspend or terminate your access if you violate these terms or abuse the service. You may delete your account and data at any time.
            </p>
          </section>

          <section>
            <h2 className="display text-2xl mb-3">Changes</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              We may update these terms as the service evolves. If we make material changes, we will notify you by posting an updated date and, where appropriate, through the app. Continued use after changes means you accept the revised terms.
            </p>
          </section>

          <section>
            <h2 className="display text-2xl mb-3">Contact</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Questions about these terms? Reach out at hello@musicdna.app.
            </p>
          </section>
        </div>
      </article>

      <footer className="border-t hairline">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-6 py-8">
          <div className="flex items-center gap-3">
            <Mark />
            <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
              MusicDNA · 2026
            </span>
          </div>
          <div className="flex items-center gap-4">
            <Link
              to="/privacy"
              className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground transition-colors hover:text-foreground"
            >
              Privacy
            </Link>
          </div>
        </div>
      </footer>
    </main>
  );
}

function Mark() {
  return (
    <svg
      width={14}
      height={14}
      viewBox="0 0 20 20"
      fill="none"
      aria-hidden="true"
    >
      <circle cx="6" cy="10" r="2" fill="currentColor" />
      <circle cx="14" cy="10" r="2" fill="currentColor" />
      <path
        d="M6 10c4-6 4 12 8 0"
        stroke="currentColor"
        strokeWidth="1.25"
        strokeLinecap="round"
      />
    </svg>
  );
}
