
WITH rnb_songs AS (
  INSERT INTO public.songs (
    title, artist, year, lane, primary_lane,
    movement, atmosphere, immersion, scale, community,
    perspective, confidence, tension, texture, transformation,
    polarization, tradeoff_richness, pairing_density, identity_signaling, longevity, cross_genre_mapping,
    canon_score, primary_dimensions, archetype_signals, active
  ) VALUES
    ('What''s Going On','Marvin Gaye',1971,'r_and_b','r_and_b',
      55,75,70,65,85, 75,60,55,65,55,
      20,18,13,15,10,14, 99,
      ARRAY['community','atmosphere','perspective']::text[], ARRAY['collective_empathy','earth_to_cosmos']::text[], true),
    ('Let''s Stay Together','Al Green',1972,'r_and_b','r_and_b',
      50,70,70,45,75, 55,70,40,65,40,
      16,14,12,14,10,10, 96,
      ARRAY['atmosphere','confidence','texture']::text[], ARRAY['intimate_devotion','effortless_sheen']::text[], true),
    ('Untitled (How Does It Feel)','D''Angelo',2000,'r_and_b','r_and_b',
      40,75,75,55,40, 50,55,50,70,45,
      20,16,12,14,7,10, 92,
      ARRAY['texture','atmosphere','confidence']::text[], ARRAY['raw_vulnerability','seductive_minimalism']::text[], true),
    ('Adorn','Miguel',2012,'r_and_b','r_and_b',
      55,65,60,45,60, 45,65,35,65,40,
      15,12,11,11,5,9, 82,
      ARRAY['atmosphere','confidence','texture']::text[], ARRAY['effortless_cool','hooked_sheen']::text[], true),
    ('Good Days','SZA',2020,'r_and_b','r_and_b',
      40,85,65,55,55, 65,50,45,65,60,
      18,15,12,13,4,10, 84,
      ARRAY['atmosphere','transformation','perspective']::text[], ARRAY['peace_seeking','pain_observing']::text[], true),
    ('Cranes in the Sky','Solange',2016,'r_and_b','r_and_b',
      35,90,70,60,50, 75,55,55,70,65,
      22,18,13,14,5,12, 88,
      ARRAY['atmosphere','transformation','perspective']::text[], ARRAY['self_interrogation','restless_control']::text[], true),
    ('Thinkin Bout You','Frank Ocean',2012,'r_and_b','r_and_b',
      40,80,65,45,55, 70,45,40,60,50,
      18,15,12,13,5,10, 92,
      ARRAY['perspective','atmosphere','texture']::text[], ARRAY['private_longing','soft_confession']::text[], true),
    ('Love on Top','Beyoncé',2011,'r_and_b','r_and_b',
      75,55,45,60,85, 45,80,35,55,55,
      14,12,11,13,8,10, 88,
      ARRAY['confidence','community','movement']::text[], ARRAY['celebration','ascending_release']::text[], true),
    ('Ain''t No Mountain High Enough','Marvin Gaye & Tammi Terrell',1967,'r_and_b','r_and_b',
      75,60,45,65,90, 50,75,30,55,55,
      14,12,11,13,10,10, 96,
      ARRAY['community','movement','confidence']::text[], ARRAY['uplift','duet_kinship']::text[], true),
    ('Ex-Factor','Lauryn Hill',1998,'r_and_b','r_and_b',
      40,65,60,50,40, 70,40,65,65,45,
      18,16,12,13,8,11, 94,
      ARRAY['tension','perspective','texture']::text[], ARRAY['ache','confession']::text[], true),
    ('If I Ain''t Got You','Alicia Keys',2004,'r_and_b','r_and_b',
      45,65,55,55,70, 60,65,40,60,40,
      12,12,11,12,8,9, 90,
      ARRAY['atmosphere','confidence','community']::text[], ARRAY['devotion','piano_ballad']::text[], true),
    ('No Diggity','Blackstreet',1996,'r_and_b','r_and_b',
      60,55,55,55,60, 45,70,45,60,40,
      15,12,11,12,8,9, 90,
      ARRAY['confidence','movement','texture']::text[], ARRAY['swagger','club_sheen']::text[], true),
    ('Prototype','OutKast',2003,'r_and_b','r_and_b',
      45,80,60,55,45, 65,60,40,70,65,
      20,17,12,13,6,12, 82,
      ARRAY['atmosphere','transformation','texture']::text[], ARRAY['alien_tenderness','cosmic_intimacy']::text[], true),
    ('Fallin''','Alicia Keys',2001,'r_and_b','r_and_b',
      45,70,60,50,45, 60,55,65,65,50,
      14,13,11,12,8,10, 88,
      ARRAY['tension','perspective','texture']::text[], ARRAY['need_as_collapse','piano_ache']::text[], true)
  RETURNING id, title
)
INSERT INTO public.pairings (song_a_id, song_b_id, lane, tests, hypothesis, why_good, diagnostic_weight, active)
SELECT a.id, b.id, 'r_and_b', tests, hypothesis, why_good, diagnostic_weight, true
FROM (VALUES
  ('What''s Going On','Let''s Stay Together', ARRAY['community','atmosphere','perspective']::text[], 'Collective empathy versus intimate devotion.', 'Tests whether R&B is public care or private surrender.', 98),
  ('Untitled (How Does It Feel)','Adorn', ARRAY['texture','confidence','atmosphere']::text[], 'Raw vulnerability versus effortless cool.', 'Stripped nerve versus polished seduction.', 96),
  ('Good Days','Cranes in the Sky', ARRAY['atmosphere','transformation','perspective']::text[], 'Peace-seeking versus pain-observing.', 'For listeners whose R&B is really about repair.', 97),
  ('Thinkin Bout You','Love on Top', ARRAY['perspective','confidence','community']::text[], 'Private longing versus public celebration.', 'Rewarding inward confession or bright arrival.', 93),
  ('Prototype','Love on Top', ARRAY['transformation','confidence','atmosphere']::text[], 'Alien tenderness versus maximal uplift.', 'Trust weirdness or trust payoff.', 90),
  ('Ain''t No Mountain High Enough','Ex-Factor', ARRAY['community','tension','perspective']::text[], 'Uplift versus ache.', 'R&B as rescue or R&B as confession.', 91),
  ('If I Ain''t Got You','Fallin''', ARRAY['confidence','tension','texture']::text[], 'Need as promise versus need as collapse.', 'Reveals the listener''s emotional threshold fast.', 92),
  ('Ex-Factor','No Diggity', ARRAY['tension','confidence','texture']::text[], 'Bruise versus cool.', 'Exposed wound or guarded charm.', 94),
  ('What''s Going On','Prototype', ARRAY['community','transformation','atmosphere']::text[], 'Social witness versus cosmic intimacy.', 'Outward empathy or inward bloom.', 95),
  ('Let''s Stay Together','If I Ain''t Got You', ARRAY['atmosphere','confidence','community']::text[], 'Steady devotion versus absolute claim.', 'Love as maintenance or as declaration.', 89),
  ('Good Days','Adorn', ARRAY['atmosphere','texture','transformation']::text[], 'Healing room versus velvet lure.', 'Space or touch.', 94),
  ('Cranes in the Sky','Untitled (How Does It Feel)', ARRAY['perspective','texture','atmosphere']::text[], 'Self-scrutiny versus surrender.', 'Emotional control or emotional exposure.', 95)
) AS p(song_a_title, song_b_title, tests, hypothesis, why_good, diagnostic_weight)
JOIN rnb_songs a ON a.title = p.song_a_title
JOIN rnb_songs b ON b.title = p.song_b_title;
